#export DATE_SOCKET_MON=6004
export DATE_DB_MYSQL_DB=DATE_CONFIG
echo "DATE_DB_MYSQL_DB="$DATE_DB_MYSQL_DB

export DATE_DB_MYSQL_USER=daq
echo "DATE_DB_MYSQL_USER="$DATE_DB_MYSQL_USER

export DATE_DB_MYSQL_PWD=daq
echo "DATE_DB_MYSQL_PWD="$DATE_DB_MYSQL_PWD

export DATE_DB_MYSQL_HOST=miceraid4
echo "DATE_DB_MYSQL_HOST="$DATE_DB_MYSQL_HOST

export DATE_SITE=/dateSite
echo "DATE_SITE="$DATE_SITE

#export DATE_HOSTNAME=miceonrec01a
export DATE_HOSTNAME=$HOSTNAME
echo "DATE_HOSTNAME="$DATE_HOSTNAME

export MICE_MON=//monitoring
echo "MICE_MON="$MICE_MON

